"""The launchd job.

A plist in ~/Library/LaunchAgents is world-readable, so credentials must not be
written into it. Sourcing one protected file also covers refresh-token auth,
where the secret is generated by discovery and never typed by the user at all.
"""

import plistlib
import textwrap

import pytest

from courtbot.__main__ import main

CONFIG = """
club:
  name: "Harbour Club Chelsea"
window:
  advance_days: 9
  release_time: "08:00"
  timezone: Europe/London
targets:
  - weekday: saturday
    times: ["10:00"]
"""


@pytest.fixture
def project(tmp_path, monkeypatch):
    (tmp_path / "config.yaml").write_text(textwrap.dedent(CONFIG))
    monkeypatch.chdir(tmp_path)
    return tmp_path


def build(project, *extra):
    out = project / "job.plist"
    assert main(["install-launchd", "--output", str(out), *extra]) == 0
    with out.open("rb") as fh:
        return plistlib.load(fh)


def test_writes_a_valid_plist(project):
    d = build(project)
    assert d["Label"] == "com.courtbot.chelsea"
    assert d["ProgramArguments"][0] == "/bin/zsh"


def test_no_credentials_are_written_into_the_plist(project):
    d = build(project)
    assert "EnvironmentVariables" not in d
    assert "SET_ME" not in str(d)


def test_the_job_sources_the_secrets_file(project):
    command = build(project)["ProgramArguments"][2]
    assert "captured/secrets.env" in command
    assert "-m courtbot snipe" in command


def test_a_custom_secrets_file_is_honoured(project):
    command = build(project, "--env-file", "~/private/dl.env")["ProgramArguments"][2]
    assert "~/private/dl.env" in command


def test_it_fires_before_the_release_not_at_it(project):
    d = build(project, "--lead", "5")
    assert (d["StartCalendarInterval"]["Hour"],
            d["StartCalendarInterval"]["Minute"]) == (7, 55)


def test_the_lead_can_cross_the_hour(project):
    d = build(project, "--lead", "15")
    assert (d["StartCalendarInterval"]["Hour"],
            d["StartCalendarInterval"]["Minute"]) == (7, 45)


def test_it_tracks_a_non_default_release_time(project):
    (project / "config.yaml").write_text(
        textwrap.dedent(CONFIG).replace('"08:00"', '"07:30"'))
    d = build(project, "--lead", "3")
    assert (d["StartCalendarInterval"]["Hour"],
            d["StartCalendarInterval"]["Minute"]) == (7, 27)


def test_paths_with_spaces_are_quoted(tmp_path, monkeypatch):
    # A project under "~/My Documents" must not split into two arguments.
    spaced = tmp_path / "my courts"
    spaced.mkdir()
    (spaced / "config.yaml").write_text(textwrap.dedent(CONFIG))
    monkeypatch.chdir(spaced)
    out = spaced / "job.plist"
    assert main(["install-launchd", "--output", str(out)]) == 0
    with out.open("rb") as fh:
        command = plistlib.load(fh)["ProgramArguments"][2]
    assert f"cd '{spaced}'" in command


def test_it_names_the_variables_the_config_actually_uses(project, capsys):
    (project / "config.yaml").write_text(
        textwrap.dedent(CONFIG) + "\nusername_env: MY_USER\npassword_env: MY_PASS\n")
    (project / "captured").mkdir()
    (project / "captured" / "secrets.env").write_text("# placeholder\n")
    build(project)
    printed = capsys.readouterr().out
    assert "MY_USER" in printed and "MY_PASS" in printed
